Repository denysdovhan/purifier-card, pull requests merged in 2020-10, with the labels that each got.

#4 Replace vacuum by purifier to fix the PurifierCardEditor
  CONTRIBUTING.md
  README.md
  src/purifier-card-editor.js
  src/purifier-card.js
Labels: bug

#5 Add Turkish translation
  README.md
  src/localize.js
  src/translations/tr.json
Labels: enhancement

#7 Add French translation
  README.md
  src/localize.js
  src/translations/fr.json
Labels: enhancement

#10 Create nb.json
  src/translations/nb.json
Labels: enhancement

#9 Update localize.js
  src/localize.js
Labels: enhancement

#11 Update README.md
  README.md
Labels: enhancement

#12 Update readme for 2h
  README.md
Labels: documentation
